version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      # temporary workaround while we get separate testing stage working
      - CI=true npm run test

artifacts:
  files:
    - '**/*'
