const categories = [
  'MISSION TERRACE CONVALESCENT HOSPITAL - SKILLED NURSING FACILITY',
  'ALTO LUCERO TRANSITIONAL CARE - SKILLED NURSING FACILITY',
  'GOLETA VALLEY COTTAGE HOSPITAL - INTENSIVE CARE',
  'GOLETA VALLEY COTTAGE HOSPITAL	- UNSPECIFIED GENERAL ACUTE CARE',
  'LOMPOC VALLEY MEDICAL CENTER - INTENSIVE CARE	',
  'LOMPOC VALLEY MEDICAL CENTER - PERINATAL',
  'LOMPOC VALLEY MEDICAL CENTER - UNSPECIFIED GENERAL ACUTE CARE',
  'MARIAN REGIONAL MEDICAL CENTER	- CORONARY CARE	',
  'MARIAN REGIONAL MEDICAL CENTER	- INTENSIVE CARE NEWBORN NURSERY',
  'MARIAN REGIONAL MEDICAL CENTER	- PERINATAL	',
  'MARIAN REGIONAL MEDICAL CENTER	- PEDIATRIC	',
  'MARIAN REGIONAL MEDICAL CENTER	- UNSPECIFIED GENERAL ACUTE CARE',
  'COTTAGE REHABILITATION HOSPITAL - REHABILITATION',
  'SANTA YNEZ VALLEY COTTAGE HOSPITAL	- UNSPECIFIED GENERAL ACUTE CARE',
  'CASA DORINDA - SKILLED NURSING	',
  'COUNTRY OAKS CARE CENTER - SKILLED NURSING	',
  'HILLSIDE HOUSE INC	- INTERMEDIATE CARE/DD	',
  'SANTA MARIA CARE CENTER - SKILLED',
  'LOMPOC VALLEY MEDICAL CENTER COMPREHENSIVE CARE CENTER D/P SNF	',
  'SAMARKAND SKILLED NURSING FACILITY	- SKILLED NURSING	',
  'THE CALIFORNIAN - SKILLED NURSING	',
  'ATTERDAG CARE CENTER - SKILLED NURSING	 ',
  'VALLE VERDE HEALTH FACILITY - SKILLED NURSING',
  'VALLE VERDE HEALTH FACILITY - SKILLED NURSING',
  'VILLA MARIA POST ACUTE	- SKILLED NURSING	',
  'MILTON HOUSE - INTERMEDIATE CARE/DD HABILITATIVE',
  'MARIAN REGIONAL MEDICAL CENTER DP/SNF	',
  'SANTA BARBARA COTTAGE HOSPITAL	- INTENSIVE CARE',
  'SANTA BARBARA COTTAGE HOSPITAL	- INTENSIVE CARE NEWBORN NURSERY',
  'SANTA BARBARA COTTAGE HOSPITAL	- PERINATAL	',
  'SANTA BARBARA COTTAGE HOSPITAL	- PEDIATRIC	',
  'SANTA BARBARA COTTAGE HOSPITAL	- UNSPECIFIED GENERAL ACUTE CARE',
  'CORNERSTONE HOUSE OF SANTA BARBARA	- INTERMEDIATE CARE/DD HABILITATIVE	',
  'BUENA VISTA CARE CENTER - SKILLED NURSING	',
  'SANTA BARBARA COUNTY PSYCHIATRIC HEALTH FACILITY - PSYCHIATRIC HEALTH	',
  'LA PALOMA GROUP HOME - INTERMEDIATE CARE/DD HABILITATIVE	',
  'ORCUTT HOUSE - INTERMEDIATE CARE/DD HABILITATIVE	',
  'SCHOOL STREET HOUSE - INTERMEDIATE CARE/DD HABILITATIVE',
  'JESSICA HOUSE	- INTERMEDIATE CARE/DD NURSING	',
  'SERENITY HOUSE	- HOSPICE',
  'SANTA BARBARA COTTAGE HOSPITAL - D/P APH - ACUTE PSYCHIATRIC CARE	',
  'LOMPOC SKILLED NURSING & REHABILITATION CENTER	- SKILLED NURSING	',
  'SANTA BARBARA ARTIFICIAL KIDNEY CENTER LLC	- DIALYSIS STATIONS	',
  'CENTRAL COAST KIDNEY CENTER - DIALYSIS STATIONS	',
  'CASA DEL MAR - INTERMEDIATE CARE/DD HABILITATIVE',
  'ALSANA - SANTA BARBARA	- CONGREGATE LIVING HEALTH FACILITY	'
];

const data = [
  [
    138,
    156,
    8,
    44,
    6,
    6,
    48,
    20,
    21,
    42,
    8,
    135,
    38,
    11,
    52,
    59,
    59,
    55,
    110,
    63,
    68,
    50,
    80,
    81,
    6,
    95,
    65,
    22,
    37,
    55,
    282,
    6,
    150,
    16,
    6,
    6,
    6,
    6,
    18,
    20,
    120,
    38,
    42,
    6,
    6
  ]
];

export const SBHealthCareFacityBedOptions: Highcharts.Options = {
  tooltip: {
    valueDecimals: 0,
    valuePrefix: '',
    valueSuffix: ' '
  },
  chart: {
    zoomType: 'xy',
    panning: { enabled: true },
    panKey: 'shift'
  },
  title: {
    text:
      'Licensed and Certified Healthcare Facility Bed Types and Counts in Santa Barbara County',
    widthAdjust: -100
  },
  subtitle: {
    text: 'as of April 6th, 2020'
  },
  xAxis: {
    type: 'category',
    categories: categories
  },
  yAxis: {
    title: {
      text: ' Bed Capacity'
    }
  },
  plotOptions: {
    series: {
      allowPointSelect: true,
      stacking: 'normal'
    },
    column: {
      allowPointSelect: true,
      stacking: 'normal'
    }
  },
  series: [
    {
      name: 'Bed capacity',
      type: 'column',
      data: data[0]
    }
  ]
};
