/*
 * Action Constants
 */

export const FETCH_ALL_METADATA = 'FETCH_ALL_METADATA';
export const FETCH_ENTIRE_DATASET = 'FETCH_ENTIRE_DATASET';
export const FETCH_DATASET_COLUMNS = 'FETCH_DATASET_COLUMNS';
